FROM mtgupf/essentia

# update system package & installation
RUN apt-get update -y && apt-get install -y python3-pip libav-tools 
WORKDIR /SoloLa
RUN git clone https://github.com/SoloLa-Platform/SoloLa
RUN cd Solola
RUN sh prerequisites.sh
